name: Setup Environment
description: "Installs dependencies and generates protobuf files"

runs:
  using: 'composite'
  
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.23'
        check-latest: true
        cache-dependency-path: '**/*.sum'

    - name: verify go version
      run: go version
      shell: bash 

    - name: Install protoc
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
      shell: bash
    
    - name: Install protogen plugins
      id: go-bin-cache
      uses: actions/cache@v4
      with:
        path: |
          ~/go/bin/protoc-gen-go
          ~/go/bin/protoc-gen-go-grpc
          ~/go/bin/wire
          ~/go/bin/mockery
          ~/go/bin/goose
        key: ${{ runner.os }}-go-bin-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-bin-

    - name: Install project required tools
      if: steps.go-bin-cache.outputs.cache-hit != 'true'
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        go install github.com/google/wire/cmd/wire@latest
        go install github.com/vektra/mockery/v2@v2.53.2
        go install github.com/pressly/goose/v3/cmd/goose@latest
      shell: bash
    
    # Install Java (Required for OpenAPI Generator)
    - name: Install Java
      run: |
        sudo apt update
        sudo apt install -y openjdk-17-jdk
        java -version
      shell: bash

    # Cache OpenAPI Generator CLI
    - name: Cache OpenAPI Generator CLI
      id: cache-openapi
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/openapi-generator-cli.jar
        key: openapi-generator-${{ runner.os }}-7.12.0
        restore-keys: |
          openapi-generator-${{ runner.os }}-

    # Install OpenAPI Generator CLI if not cached
    - name: Install OpenAPI Generator CLI
      if: steps.cache-openapi.outputs.cache-hit != 'true'
      run: |
        OPENAPI_VERSION="7.12.0"
        wget "https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/${OPENAPI_VERSION}/openapi-generator-cli-${OPENAPI_VERSION}.jar" -O /usr/local/bin/openapi-generator-cli.jar
      shell: bash
    
    - name: Create OpenAPI Generator Symlink
      run: |
        echo '#!/bin/bash' | sudo tee /usr/local/bin/openapi-generator > /dev/null
        echo 'exec java -jar /usr/local/bin/openapi-generator-cli.jar "$@"' | sudo tee -a /usr/local/bin/openapi-generator > /dev/null
        sudo chmod +x /usr/local/bin/openapi-generator
        openapi-generator version
      shell: bash
