name: Setup Environment
description: "Installs dependencies and generates protobuf files"

runs:
  using: 'composite'
  
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.23'
        check-latest: true
        cache-dependency-path: '**/*.sum'

    - name: verify go version
      run: go version
      shell: bash 

    - name: Install protoc
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
      shell: bash
    
    - name: Install protogen plugins
      id: protogen-cache
      uses: actions/cache@v4
      with:
        path: |
          ~/go/bin/protoc-gen-go
          ~/go/bin/protoc-gen-go-grpc
        key: ${{ runner.os }}-protocgen-${{ hashFiles('**/go.sum') }}

    - name: Install project required tools
      if: steps.protogen-cache.outputs.cache-hit != 'true'
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        go install github.com/google/wire/cmd/wire@latest
        go install github.com/vektra/mockery/v2@v2.46.0
        go install github.com/pressly/goose/v3/cmd/goose@latest
      shell: bash

    - name: Setup dependency
      run: go mod tidy -e
      shell: bash

    - name: generate the required files
      run: source .envrc.test && make generate
      shell: bash