generatorName: go
inputSpec: openapi/docs/api.yaml
outputDir: openapi/generated/go/openapi
templateDir: openapi/goTemplates
globalProperties:
  models: ""
  supportingFiles: "utils.go"
additionalProperties:
  packageName: "openapi"
  generateMarshalJSON: true
  generateUnmarshalJSON: true
  omitEmptyFields: false
typeMappings:
  int32: int
  float32: float64
  double: float64
importMappings:
  