// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Order struct {
	ID          string `json:"id"`
	UserID      string `json:"userId"`
	AmountCents string `json:"amountCents"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type PaginationMetadata struct {
	Offset   int32 `json:"offset"`
	PageSize int32 `json:"pageSize"`
	Count    int32 `json:"count"`
	HasMore  bool  `json:"hasMore"`
	Total    *int  `json:"total,omitempty"`
}

type PaginationParams struct {
	Offset       int32 `json:"offset"`
	PageSize     int32 `json:"pageSize"`
	IncludeTotal bool  `json:"includeTotal"`
}

type Query struct {
}

type Subscription struct {
}

type Time struct {
	UnixTime  int32  `json:"unixTime"`
	Timestamp string `json:"timestamp"`
}

type User struct {
	ID        string   `json:"id"`
	Email     string   `json:"email"`
	Age       int32    `json:"age"`
	CreatedAt string   `json:"createdAt"`
	UpdatedAt string   `json:"updatedAt"`
	Orders    []*Order `json:"orders"`
}

type UserCreateInput struct {
	Email string `json:"email"`
	Age   int32  `json:"age"`
}

type UsersWithPagination struct {
	Users    []*User             `json:"users"`
	PageInfo *PaginationMetadata `json:"pageInfo"`
}
