// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"
	"log/slog"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function for the type MockService
func (_mock *MockService) Debug(msg string, args ...slog.Attr) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockService_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockService_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - msg string
//   - args ...slog.Attr
func (_e *MockService_Expecter) Debug(msg interface{}, args ...interface{}) *MockService_Debug_Call {
	return &MockService_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{msg}, args...)...)}
}

func (_c *MockService_Debug_Call) Run(run func(msg string, args ...slog.Attr)) *MockService_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []slog.Attr
		var variadicArgs []slog.Attr
		if len(args) > 1 {
			variadicArgs = args[1].([]slog.Attr)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockService_Debug_Call) Return() *MockService_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_Debug_Call) RunAndReturn(run func(msg string, args ...slog.Attr)) *MockService_Debug_Call {
	_c.Run(run)
	return _c
}

// DebugContext provides a mock function for the type MockService
func (_mock *MockService) DebugContext(ctx context.Context, msg string, args ...slog.Attr) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// MockService_DebugContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DebugContext'
type MockService_DebugContext_Call struct {
	*mock.Call
}

// DebugContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...slog.Attr
func (_e *MockService_Expecter) DebugContext(ctx interface{}, msg interface{}, args ...interface{}) *MockService_DebugContext_Call {
	return &MockService_DebugContext_Call{Call: _e.mock.On("DebugContext",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *MockService_DebugContext_Call) Run(run func(ctx context.Context, msg string, args ...slog.Attr)) *MockService_DebugContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []slog.Attr
		var variadicArgs []slog.Attr
		if len(args) > 2 {
			variadicArgs = args[2].([]slog.Attr)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockService_DebugContext_Call) Return() *MockService_DebugContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_DebugContext_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...slog.Attr)) *MockService_DebugContext_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type MockService
func (_mock *MockService) Error(msg string, args ...slog.Attr) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockService_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockService_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - msg string
//   - args ...slog.Attr
func (_e *MockService_Expecter) Error(msg interface{}, args ...interface{}) *MockService_Error_Call {
	return &MockService_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{msg}, args...)...)}
}

func (_c *MockService_Error_Call) Run(run func(msg string, args ...slog.Attr)) *MockService_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []slog.Attr
		var variadicArgs []slog.Attr
		if len(args) > 1 {
			variadicArgs = args[1].([]slog.Attr)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockService_Error_Call) Return() *MockService_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_Error_Call) RunAndReturn(run func(msg string, args ...slog.Attr)) *MockService_Error_Call {
	_c.Run(run)
	return _c
}

// ErrorContext provides a mock function for the type MockService
func (_mock *MockService) ErrorContext(ctx context.Context, msg string, args ...slog.Attr) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// MockService_ErrorContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrorContext'
type MockService_ErrorContext_Call struct {
	*mock.Call
}

// ErrorContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...slog.Attr
func (_e *MockService_Expecter) ErrorContext(ctx interface{}, msg interface{}, args ...interface{}) *MockService_ErrorContext_Call {
	return &MockService_ErrorContext_Call{Call: _e.mock.On("ErrorContext",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *MockService_ErrorContext_Call) Run(run func(ctx context.Context, msg string, args ...slog.Attr)) *MockService_ErrorContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []slog.Attr
		var variadicArgs []slog.Attr
		if len(args) > 2 {
			variadicArgs = args[2].([]slog.Attr)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockService_ErrorContext_Call) Return() *MockService_ErrorContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_ErrorContext_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...slog.Attr)) *MockService_ErrorContext_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type MockService
func (_mock *MockService) Info(msg string, args ...slog.Attr) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockService_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockService_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - args ...slog.Attr
func (_e *MockService_Expecter) Info(msg interface{}, args ...interface{}) *MockService_Info_Call {
	return &MockService_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{msg}, args...)...)}
}

func (_c *MockService_Info_Call) Run(run func(msg string, args ...slog.Attr)) *MockService_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []slog.Attr
		var variadicArgs []slog.Attr
		if len(args) > 1 {
			variadicArgs = args[1].([]slog.Attr)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockService_Info_Call) Return() *MockService_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_Info_Call) RunAndReturn(run func(msg string, args ...slog.Attr)) *MockService_Info_Call {
	_c.Run(run)
	return _c
}

// InfoContext provides a mock function for the type MockService
func (_mock *MockService) InfoContext(ctx context.Context, msg string, args ...slog.Attr) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// MockService_InfoContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InfoContext'
type MockService_InfoContext_Call struct {
	*mock.Call
}

// InfoContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...slog.Attr
func (_e *MockService_Expecter) InfoContext(ctx interface{}, msg interface{}, args ...interface{}) *MockService_InfoContext_Call {
	return &MockService_InfoContext_Call{Call: _e.mock.On("InfoContext",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *MockService_InfoContext_Call) Run(run func(ctx context.Context, msg string, args ...slog.Attr)) *MockService_InfoContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []slog.Attr
		var variadicArgs []slog.Attr
		if len(args) > 2 {
			variadicArgs = args[2].([]slog.Attr)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockService_InfoContext_Call) Return() *MockService_InfoContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_InfoContext_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...slog.Attr)) *MockService_InfoContext_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type MockService
func (_mock *MockService) Warn(msg string, args ...slog.Attr) {
	if len(args) > 0 {
		_mock.Called(msg, args)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockService_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockService_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - msg string
//   - args ...slog.Attr
func (_e *MockService_Expecter) Warn(msg interface{}, args ...interface{}) *MockService_Warn_Call {
	return &MockService_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{msg}, args...)...)}
}

func (_c *MockService_Warn_Call) Run(run func(msg string, args ...slog.Attr)) *MockService_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []slog.Attr
		var variadicArgs []slog.Attr
		if len(args) > 1 {
			variadicArgs = args[1].([]slog.Attr)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockService_Warn_Call) Return() *MockService_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_Warn_Call) RunAndReturn(run func(msg string, args ...slog.Attr)) *MockService_Warn_Call {
	_c.Run(run)
	return _c
}

// WarnContext provides a mock function for the type MockService
func (_mock *MockService) WarnContext(ctx context.Context, msg string, args ...slog.Attr) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// MockService_WarnContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WarnContext'
type MockService_WarnContext_Call struct {
	*mock.Call
}

// WarnContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...slog.Attr
func (_e *MockService_Expecter) WarnContext(ctx interface{}, msg interface{}, args ...interface{}) *MockService_WarnContext_Call {
	return &MockService_WarnContext_Call{Call: _e.mock.On("WarnContext",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *MockService_WarnContext_Call) Run(run func(ctx context.Context, msg string, args ...slog.Attr)) *MockService_WarnContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []slog.Attr
		var variadicArgs []slog.Attr
		if len(args) > 2 {
			variadicArgs = args[2].([]slog.Attr)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockService_WarnContext_Call) Return() *MockService_WarnContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_WarnContext_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...slog.Attr)) *MockService_WarnContext_Call {
	_c.Run(run)
	return _c
}
