// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// SayHello provides a mock function for the type MockService
func (_mock *MockService) SayHello(ctx context.Context, name string) (string, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for SayHello")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_SayHello_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SayHello'
type MockService_SayHello_Call struct {
	*mock.Call
}

// SayHello is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockService_Expecter) SayHello(ctx interface{}, name interface{}) *MockService_SayHello_Call {
	return &MockService_SayHello_Call{Call: _e.mock.On("SayHello", ctx, name)}
}

func (_c *MockService_SayHello_Call) Run(run func(ctx context.Context, name string)) *MockService_SayHello_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_SayHello_Call) Return(s string, err error) *MockService_SayHello_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_SayHello_Call) RunAndReturn(run func(ctx context.Context, name string) (string, error)) *MockService_SayHello_Call {
	_c.Call.Return(run)
	return _c
}
