env: dev
http_server:
  enabled: true
  port: 8082
  health_check_endpoint: "/health-check"
  profiler_endpoint: "/debug"
  allowed_origins:
    - "http://localhost:*"

logging:
  level: debug

database:
  url: "" # load from env
  enable_log: true

grpc_server:
  enabled: false
  port: 30082