env: prod
version: "prod" # override by git hash from .envrc
http_server:
  server_name: "httpServer"
  enabled: true
  port: 8083
  health_check_endpoint: "/health-check"
  profiler_endpoint: "/debug"
  allowed_origins:
    - ""

grpc_server:
  enabled: false
  port: 30083

tracing:
  enabled: false
  jaeger_endpoint: "localhost:4318"
  service_name: "Server"
  service_version: "prod" # override by git hash from .envrc

logging:
  level: info
  writer: stdout
  use_json: true
  add_source: true
  source_key: "source"

database:
  url: "" # override by env
  logger:
    writer: stdout
    level: info
    show_sql_params: false
    slow_threshold_in_seconds: 1
