env: dev
version: "dev" # override by git hash from .envrc
http_server:
  server_name: "httpServer"
  enabled: true
  port: 8082
  health_check_endpoint: "/health-check"
  profiler_endpoint: "/debug"
  allowed_origins:
    - "http://localhost:*"

grpc_server:
  enabled: false
  port: 30082

tracing:
  enabled: true
  jaeger_endpoint: "localhost:4318"
  service_name: "Server"
  service_version: "dev" # override by git hash from .envrc

logging:
  level: debug
  writer: stdout
  use_json: false
  add_source: true
  source_key: "source"

database:
  url: "postgres://test_user:test_password@localhost:5433/goWebapp_test" # override by env
  logger:
    level: info
    writer: stdout
    show_sql_params: true
    slow_threshold_in_seconds: 1
