env: prod
http_server:
  enabled: true
  port: 8083
  health_check_endpoint: "/health-check"
  profiler_endpoint: "/debug"
  allowed_origins:
    - ""

logging:
  level: info

database:
  url: "" # load from env
  enable_log: true

grpc_server:
  enabled: false
  port: 30083