env: dev
http_server:
  enabled: true
  port: 8082
  health_check_endpoint: "/health-check"
  profiler_endpoint: "/debug"
  allowed_origins:
    - "http://localhost:*"

grpc_server:
  enabled: false
  port: 30082

tracing:
  enabled: true
  jaeger_endpoint: "localhost:4318"
  tracer_name: "http.server"
  service_name: "Server"
  service_version: "0.0.1"

logging:
  level: debug

database:
  url: "" # load from env
  enable_log: true
