env: prod
http_server:
  enabled: true
  port: 8083
  health_check_endpoint: "/health-check"
  profiler_endpoint: "/debug"
  allowed_origins:
    - ""

grpc_server:
  enabled: false
  port: 30083

tracing:
  enabled: false
  jaeger_endpoint: ""
  service_name: ""
  service_version: ""

logging:
  level: info

database:
  url: "" # load from env
  enable_log: false
