name: Go build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested # when use merge group

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Database
        uses: ./.github/workflows/setup-db.yaml

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Setup dependency
        run: go mod tidy -e

      - name: generate the required files
        run: source .envrc.test && make generate
        shell: bash

      - name: Run tests
        run: make test ARGS="-v"
