name: Setup DB

on:
  workflow_call:

jobs:
  setup-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: goWebapp_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
